# Generated by Django 5.2.7 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0007_auto_20250329_2337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataupdatesettings",
            name="max_allowed_year",
            field=models.IntegerField(default=2026),
        ),
    ]
