# Generated by Django 3.2.20 on 2025-10-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0040_alter_course_school'),
        ('analytics', '0022_uierrorlog_squashed_0024_alter_uierrorlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDropStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_total_enrolment', models.IntegerField(blank=True, null=True)),
                ('final_total_enrolment', models.IntegerField(blank=True, null=True)),
                ('baseline_captured_at', models.DateTimeField(blank=True, null=True)),
                ('final_captured_at', models.DateTimeField(blank=True, null=True)),
                ('drop_rate', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.semester')),
            ],
        ),
    ]
