# Generated by Django 5.2.7 on 2026-02-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0023_coursedropstats"),
        ("timetable", "0041_alter_course_related_courses"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDropRateAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("historical_drop_rate", models.FloatField(blank=True, null=True)),
                ("semesters_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.course",
                    ),
                ),
            ],
        ),
    ]
