# Generated by Django 5.2.7 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0040_alter_course_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="related_courses",
            field=models.ManyToManyField(blank=True, to="timetable.course"),
        ),
    ]
