# Generated by Django 5.2.7 on 2026-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0046_delete_registrationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="friends",
            field=models.ManyToManyField(blank=True, to="student.student"),
        ),
    ]
